### ISSUE TITLE
Artifacts are expired

### ISSUE THREAD

**Issue by gigatexel** [hartimcwildfly/bmw-zgw-discovery#1]
Hi, I'm looking for the MacOS version, but all artifacs are expired and the binaries cannot be downloaded.

https://github.com/hartimcwildfly/bmw-zgw-discovery/actions

**Comment by hartimcwildfly** [comment]
Let me do a dummy commit then these should be rebuilt.

**Comment by hartimcwildfly** [comment]
The artifacts are available again [here](https://github.com/hartimcwildfly/bmw-zgw-discovery/actions/runs/4231640612)
Please let me know if it works on MacOs as I never got any feedback for the Mac version

**Comment by gigatexel** [comment]
I'm afraid not

<img width="668" alt="image" src="https://user-images.githubusercontent.com/65073191/220319312-a2097d94-e1f2-4653-a368-40ff959aa7b2.png">

**Comment by hartimcwildfly** [comment]
ok let me have a look at this this evening...
