### ISSUE TITLE
MacOS binary does not work

### ISSUE THREAD

**Issue by hartimcwildfly** [hartimcwildfly/bmw-zgw-discovery#2]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/65073191/220319312-a2097d94-e1f2-4653-a368-40ff959aa7b2.png">

_Originally posted by @gigatexel in https://github.com/hartimcwildfly/bmw-zgw-discovery/issues/1#issuecomment-1438232467_

**Comment by hartimcwildfly** [comment]
@gigatexel did you choose the right version? x64 / ARM? Can you show the first few lines? The output seems to be incomplete. For me it looks like the binary is not executed. Instead it is printed to terminal.

**Comment by hartimcwildfly** [comment]
@gigatexel I was right. What you see is the binary code interpreted as text. How did you open/started the executable?

**Comment by gigatexel** [comment]
`chmod +x BmwDiscovery` and then executing with `./BmwDiscovery` did the trick :-)
I don't know if this can be integrated in the build? Or maybe just put this in the docs.

**Comment by hartimcwildfly** [comment]
Ok I will check how it's stored in the zip archive. But maybe this is automatically done by MacOs to prevent executing potentially unsafe code. I will add it to the documentation. Thanks for the feedback
